### ISSUE TITLE
能换成claude的官方logo么，这个logo太丑了

### ISSUE THREAD

**Issue by XiaoboAlexander** [jtsang4/bob-plugin-claude-translator#1]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

我找到一个logo下载链接：https://www.iconfont.cn/search/index?searchType=icon&q=claude

### 描述 Motivation

更好看了，更有下载欲望

### Solution

可以用这个logo，链接：https://www.iconfont.cn/search/index?searchType=icon&q=claude

### 还有其他内容吗？Anything else?

无

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
哈哈，可以的，感谢提供链接。我空了改一版，以及加上流式输出的能力

**Comment by jtsang4** [comment]
已更换图标，并支持流式输出，欢迎更新到 0.4.0 版本。
