### ISSUE TITLE
是否可以自定义prompt

### ISSUE THREAD

**Issue by ShuaiJerry** [jtsang4/bob-plugin-claude-translator#11]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

prompt自定义

### 描述 Motivation

自定义用于翻译的prompt

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
目前已支持自定义 Prompt
