### ISSUE TITLE
[Bug] {{接口响应错误}}

### ISSUE THREAD

**Issue by aeolusnee** [jtsang4/bob-plugin-claude-translator#14]
### Please search before asking

- [X] I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network

- [X] I am sure it is not a network issue.

### Claude Translator Bob Plugin version

0.5.5

### 系统版本 | System version

MacOS 13.6.7

### Bob version

1.9.2

### 复现步骤 | Reproduce step

填入APIkey后出现错误。在OPENCAT使用正常

### 你看到了什么错误？What errors do you see?

接口响应错误

### 你期望看到什么？What did you expect to see?

正常工作

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by aeolusnee** [comment]
找到问题了，打扰了

**Comment by yanxiang-wang** [comment]
什么问题呢，我也遇到类似情况了
