### ISSUE TITLE
请求支持第三方API接口中专聚合服务-AiHubMix

### ISSUE THREAD

**Issue by atinst** [jtsang4/bob-plugin-claude-translator#18]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

请求支持AiHubMix提供的第三方中转Claude API

### 描述 Motivation

由于官方Claude API对地区及信用卡有一定的限制，对于小白用户不是很友好，目前该第三方中转聚合API平台可消除这些限制，请求能支持该平台的中转Claude API

### Solution

官网https://aihubmix.com/
文档https://doc.aihubmix.com/
**这不是广告**

### 还有其他内容吗？Anything else?

已经尝试填入API并将Base URL设置为https://aihubmix.com ，但是报接口错误

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
暂未计划接入广告，更何况这个是 OpenAI 格式的服务
