### ISSUE TITLE
能否支持Claude 2

### ISSUE THREAD

**Issue by realCrush** [jtsang4/bob-plugin-claude-translator#4]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

Claude 2已经推出并支持API使用，此插件能否支持？

### 描述 Motivation

使用Claude 2 API完成翻译、润色等任务，Claude 2介绍：https://www.anthropic.com/index/claude-2

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
这周空了就支持上，暂时也可以先用 http://github.com/jtsang4/claude-to-chatgpt 把 API 转换成 OpenAI 的 API 格式来使用 OpenAI 的 bob 插件

**Comment by realCrush** [comment]
已经靠你提到的 [http://github.com/jtsang4/claude-to-chatgpt](https://github.com/jtsang4/claude-to-chatgpt) 实现了转换，但每次都要开docker还是有点麻烦的，也占资源，可以的话还是更新一下bob的插件吧，另外这个插件能否顺便支持一下自定义prompt呢

**Comment by jtsang4** [comment]
目前已支持 claude-2，但实测效果不如 claude-v1.3，不清楚是否和新版本 API 调用方式变化了有关，尊需要可以更新插件到最新版本试试看。
