### ISSUE TITLE
[Bug] {{长内容偶发性出现json截断}}

### ISSUE THREAD

**Issue by moxi000** [jtsang4/bob-plugin-claude-translator#5]
### Please search before asking

- [X] I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network

- [X] I am sure it is not a network issue.

### Claude Translator Bob Plugin version

v0.4.0

### 系统版本 | System version

macos14

### Bob version

v1.8

### 复现步骤 | Reproduce step

对长文档进行翻译时，偶发性的出现json解析错误的bug，如下图。

### 你看到了什么错误？What errors do you see?

消息截断
![3b928af299f632bb02562065dd576a7e](https://github.com/jtsang4/bob-plugin-claude-translator/assets/66484370/d7bec310-b633-4020-a053-09fbe14feef8)
![0f6c892b5ea2d074a5e59860f0905d50](https://github.com/jtsang4/bob-plugin-claude-translator/assets/66484370/7ec80946-e8bc-4b8c-9791-b6622f768c0f)

### 你期望看到什么？What did you expect to see?

正常输出内容

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
最新版应该已经解决相关问题，可以更新后试试看。
