### ISSUE TITLE
翻译结果内容

### ISSUE THREAD

**Issue by JayDaniel** [jtsang4/bob-plugin-claude-translator#6]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

翻译结果取消 ```  ```

### 描述 Motivation

<img width="599" alt="image" src="https://github.com/jtsang4/bob-plugin-claude-translator/assets/9743878/5b5dd757-3b7a-47d6-b24f-f8e2b8c90dcd">

翻译结果，为啥会有符号包裹？可否考虑去掉？

```
Instant
```

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Mrered** [comment]
同样遇到了这个问题

插件版本 0.5.3
