### ISSUE TITLE
Claude 3 pls

### ISSUE THREAD

**Issue by poyih** [jtsang4/bob-plugin-claude-translator#7]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

Anthropic launched Claude 3

### 描述 Motivation

https://www.anthropic.com/news/claude-3-family

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtsang4** [comment]
I don't have a available Claude API key currently. The previous key has been recycled. If you have a available key, PR is also welcome.

**Comment by jtsang4** [comment]
Claude3 is supported now: https://github.com/jtsang4/bob-plugin-claude-translator/pull/8
