### ISSUE TITLE
Support Haiku

### ISSUE THREAD

**Issue by bs10081** [jtsang4/bob-plugin-claude-translator#9]
### Search before asking

- [X] 在 [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) 中没有找到类似的内容。I searched in the [issues](https://github.com/jtsang4/bob-plugin-claude-translator/issues) and found nothing similar.

### Feature

Support Claude Haiku Model

### 描述 Motivation

<img width="1310" alt="CleanShot 2024-03-10 at 23 02 42@2x" src="https://github.com/jtsang4/bob-plugin-claude-translator/assets/38148679/e23a4b6d-bd55-4eb6-8fde-a02137df9fe8">
Haiku is cheaper for translation, so maybe you can add to options.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by poyih** [comment]
官方都没正式发布

**Comment by missuo** [comment]
> 官方都没正式发布

早就发布了，都可以用了啊。

**Comment by jtsang4** [comment]
Haiku model is supported now.
